--1
SELECT* FROM JOB;

--2 
SELECT JOB_NAME
FROM JOB;

--3
SELECT *
FROM DEPARTMENT;

--4 
SELECT EMP_NAME,EMAIL,PHONE,HIRE_DATE
FROM EMPLOYEE;

--5
SELECT HIRE_DATE,EMP_NAME,SALARY
FROM EMPLOYEE;

--6
SELECT EMP_NAME,SALARY*12 AS 연봉,(SALARY+(SALARY*BONUS))*12 AS 총수령액,(SALARY +(SALARY * BONUS))*12-(SALARY*12)*0.03 AS 실수령액
FROM EMPLOYEE;
--7
SELECT EMP_NAME,SALARY,HIRE_DATE,PHONE
FROM EMPLOYEE
WHERE SAL_LEVEL='S1';

--8
SELECT EMP_NAME,SALARY,(SALARY+(SALARY*NVL(BONUS,0))) AS 실수령액,HIRE_DATE
FROM EMPLOYEE
WHERE (SALARY +(SALARY * BONUS))*12-(SALARY*12)*0.03>=50000000;


--9
SELECT *
FROM EMPLOYEE
WHERE SALARY>=4000000 AND JOB_CODE='J2';

--10
SELECT EMP_NAME,DEPT_CODE,HIRE_DATE
FROM EMPLOYEE
WHERE DEPT_CODE IN ('D5','D9') AND HIRE_DATE<'02/01/01' ;

--11
SELECT *
FROM EMPLOYEE
WHERE HIRE_DATE BETWEEN '90/01/01' AND '01/01/01';

--12
SELECT EMP_NAME
FROM EMPLOYEE
WHERE EMP_NAME LIKE'%연';

--13
SELECT EMP_NAME,PHONE
FROM EMPLOYEE
WHERE PHONE NOT LIKE '010%';

--14
SELECT *
FROM EMPLOYEE
WHERE EMAIL LIKE '____\_%' ESCAPE'\' 
            AND (DEPT_CODE='D9'OR DEPT_CODE='D6') 
            AND HIRE_DATE BETWEEN '90/01/01' AND'00/12/01' AND SALARY>=2700000 ;

--15
SELECT EMP_NAME,SUBSTR(EMP_NO,1,2) AS 생년, SUBSTR(EMP_NO,3,2) AS 생월, SUBSTR(EMP_NO,5,2) AS 생일 
FROM EMPLOYEE;

--16
SELECT EMP_NAME,RPAD(SUBSTR(EMP_NO,1,7),14,'*') AS 주민번호
FROM EMPLOYEE;

--17 --몰라


--18
SELECT *
FROM EMPLOYEE
WHERE MOD(EMP_ID,2)=1;

--19  -- 
SELECT *
FROM EMPLOYEE
WHERE EXTRACT(YEAR FROM SYSDATE)-EXTRACT(YEAR FROM TO_DATE(SUBSTR(HIRE_DATE,1,2),'RR'))>25;

--20
SELECT EMP_NAME,TO_CHAR(SALARY,'L999,999,999')
FROM EMPLOYEE;

--21
SELECT EMP_NAME,DEPT_CODE,
        CONCAT(SUBSTR(EMP_NO,1,2),'년 ')
        ||CONCAT(SUBSTR(EMP_NO,3,2),'월 ')
        ||CONCAT(SUBSTR(EMP_NO,5,2),'일') AS 생년월일,
        EXTRACT(YEAR FROM SYSDATE)-EXTRACT(YEAR FROM TO_DATE(SUBSTR(EMP_NO,1,2),'RR')) AS 나이
FROM EMPLOYEE;

--22
SELECT EMP_ID,EMP_NAME,DEPT_CODE,
    CASE
    WHEN DEPT_CODE='D5' THEN '총무부'
    WHEN DEPT_CODE='D6' THEN '기획부'
    WHEN DEPT_CODE='D9' THEN '영업부'
    END AS 부서
FROM EMPLOYEE
WHERE DEPT_CODE IN ('D5','D6','D9')
ORDER BY DEPT_CODE ASC;

--23
SELECT EMP_NAME,SUBSTR(EMP_NO,1,6),SUBSTR(EMP_NO,8,14),SUBSTR(EMP_NO,1,6)+SUBSTR(EMP_NO,8,14)
FROM EMPLOYEE
WHERE EMP_ID=201;

--24-----???
SELECT SUM(SALARY+(SALARY*NVL(BONUS,0)))*12 AS 보너스포함연봉합
FROM EMPLOYEE
WHERE DEPT_CODE='D5';

--25 -- 다시 풀어보기
SELECT COUNT(*) AS 전체직원수,
       COUNT(DECODE(SUBSTR(TO_CHAR(EXTRACT(YEAR FROM HIRE_DATE)),1,4),'2001','1')) AS "2001년",
       COUNT(DECODE(SUBSTR(TO_CHAR(EXTRACT(YEAR FROM HIRE_DATE)),1,4),'2002','2')) AS "2002년",
       COUNT(DECODE(SUBSTR(TO_CHAR(EXTRACT(YEAR FROM HIRE_DATE)),1,4),'2003','3')) AS "2003년",
       COUNT(DECODE(SUBSTR(TO_CHAR(EXTRACT(YEAR FROM HIRE_DATE)),1,4),'2004','4')) AS "2004년"
FROM EMPLOYEE;

--BS 연습문제
--1
SELECT EMP_NAME,EMP_NO,DEPT_TITLE,JOB_NAME 
FROM EMPLOYEE LEFT JOIN DEPARTMENT ON DEPT_CODE=DEPT_ID JOIN JOB USING(JOB_CODE) 
WHERE SUBSTR(EMP_NO,1,1)=7 AND SUBSTR(EMP_NO,8,1)=2 AND EMP_NAME LIKE '전%';
--2
SELECT ROWNUM,EMP_NAME, 나이,DEPT_TITLE,JOB_NAME
FROM (SELECT EMP_NO,EMP_NAME,EXTRACT(YEAR FROM SYSDATE)-EXTRACT(YEAR FROM TO_DATE(SUBSTR(EMP_NO,1,2),'RR')) AS 나이,DEPT_TITLE,JOB_NAME
      FROM EMPLOYEE LEFT JOIN DEPARTMENT ON DEPT_CODE=DEPT_ID
                    JOIN JOB USING(JOB_CODE)
      ORDER BY EXTRACT(YEAR FROM SYSDATE)-EXTRACT(YEAR FROM TO_DATE(SUBSTR(EMP_NO,1,2),'RR')))
WHERE ROWNUM= 1;
--3
SELECT EMP_NO,EMP_NAME,JOB_NAME
FROM EMPLOYEE  JOIN JOB USING(JOB_CODE)
WHERE EMP_NAME LIKE '%형%';
--4
SELECT EMP_NAME,JOB_NAME,DEPT_CODE,DEPT_TITLE
FROM EMPLOYEE LEFT JOIN DEPARTMENT ON DEPT_ID=DEPT_CODE
                    JOIN JOB USING(JOB_CODE)
WHERE DEPT_CODE IN('D5','D6');
--5
SELECT EMP_NAME,BONUS,DEPT_TITLE,LOCAL_NAME
FROM EMPLOYEE LEFT JOIN DEPARTMENT ON DEPT_CODE=DEPT_ID
               LEFT JOIN LOCATION ON LOCAL_CODE=LOCATION_ID
WHERE BONUS IS NOT NULL;
--6
SELECT EMP_NAME,JOB_NAME,DEPT_TITLE,LOCAL_NAME
FROM EMPLOYEE LEFT JOIN DEPARTMENT ON DEPT_CODE=DEPT_ID
                    JOIN JOB USING(JOB_CODE)
            LEFT JOIN LOCATION ON LOCAL_CODE=LOCATION_ID;
--7 
SELECT EMP_NAME,DEPT_TITLE,LOCAL_NAME,NATIONAL_NAME
FROM EMPLOYEE LEFT JOIN DEPARTMENT ON DEPT_CODE=DEPT_ID
                    JOIN JOB USING(JOB_CODE)
            LEFT JOIN LOCATION ON LOCAL_CODE=LOCATION_ID
                 JOIN NATIONAL USING(NATIONAL_CODE)
WHERE NATIONAL_NAME IN ('한국','일본');
--8
SELECT E.EMP_NAME,E.DEPT_CODE,D.EMP_NAME
FROM EMPLOYEE E JOIN EMPLOYEE D ON E.DEPT_CODE=D.DEPT_CODE
        LEFT JOIN DEPARTMENT ON E.DEPT_CODE=DEPT_ID
WHERE E.EMP_NAME!=D.EMP_NAME
ORDER BY E.EMP_NAME;
--9
SELECT EMP_NAME,JOB_NAME,SALARY
FROM EMPLOYEE JOIN JOB USING(JOB_CODE)
WHERE JOB_CODE IN('J4','J7') ;
--10 
SELECT EMP_NO,EMP_NAME,DEPT_TITLE,JOB_NAME,HIRE_DATE,ROWNUM
FROM (SELECT EMP_NO,EMP_NAME,DEPT_TITLE,JOB_NAME,HIRE_DATE,(SALARY+(SALARY*NVL(BONUS,0)))*12 AS 보너스포함연봉
        FROM EMPLOYEE LEFT JOIN DEPARTMENT ON DEPT_CODE=DEPT_ID
                    JOIN JOB USING(JOB_CODE)
                    ORDER BY (SALARY+(SALARY*NVL(BONUS,0)))*12 DESC)
WHERE ROWNUM<=5;
--11 
SELECT DEPT_TITLE,(SELECT SUM(SALARY) FROM EMPLOYEE GROUP BY DEPT_CODE) AS 부서별급여합계
FROM EMPLOYEE LEFT JOIN DEPARTMENT ON DEPT_ID=DEPT_CODE
WHERE (SELECT SUM(SALARY) FROM EMPLOYEE GROUP BY DEPT_CODE)>=(SELECT ;

--12
SELECT DEPT_TITLE,SUM(EMPLOYEE.SALARY) 
FROM EMPLOYEE LEFT JOIN DEPARTMENT ON DEPT_ID=DEPT_CODE
GROUP BY DEPT_TITLE;









                    
                    
                    
  





